root: true
extends:
  - "eslint:recommended"
env:
  node: true
  es6: true
rules:
  semi: error
overrides:
  - files: "**/*.ts"
    extends:
      - "plugin:@typescript-eslint/recommended"
    plugins:
      - "@typescript-eslint"
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: ./tsconfig.json
  - files: "**/*.spec.ts"
    env:
      jasmine: true
    plugins:
      - "jasmine"
    extends:
      - "plugin:jasmine/recommended"
